development:
  dialect: mysql
  datasource: root:@/golang_songs?charset=utf8&parseTime=True&loc=Local
  dir: db/migrations

production:
  dialect: mysql
  datasource: kt321:route666@tcp(database-2.cvzte0rjvtt7.ap-northeast-1.rds.amazonaws.com:3306)/db_goyoursongs_rds?charset=utf8&parseTime=True
  dir: db/migrations